/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author IamDuna
 */
public class benhanbenhnhan extends javax.swing.JFrame {
    /**
     * Creates new form benhanbenhnhan
     */
    private String xdoituong, xgioitinh, xketquadieutri;
    public benhanbenhnhan() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);      
    }
    /* 2 hàm SetData và GetData để lấy ID từ Jframe benhnhan sang. Sau đó sử dụng ID đó để truy vấn SELECT WHERE */
    public void SetID(String ID) {
        this.IDBN.setText(ID);
    }
    public String GetID() {
        return this.IDBN.getText();
    }
    /* ******** */

    private void LoadData() {  
            String onetwothree = IDBN.getText();
        //hàm hiện thị thông tin từ sql về bảng
         try{ 
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/QLBV","root","");
            Statement st = conn.createStatement();
            String sql = "SELECT * FROM benhnhan WHERE id=?";
            PreparedStatement pstmt = conn.prepareStatement(sql);
            pstmt.setString(1,onetwothree);
            ResultSet rs = pstmt.executeQuery();
            while(rs.next()){
                ahoten.setText(rs.getString("hoten"));
                angaysinh.setText(rs.getString("ngaysinh"));
                /* Set lựa chọn của buttongroup giới tính */
                switch(rs.getString("gioitinh")){ 
                    case "Nam":
                        RBnam.setSelected(true);
                        break;
                    case "Nữ":
                        RBnu.setSelected(true);
                        break;
                    default:
                        btngroupGioiTinh.clearSelection();
                }
                /* *********************** */
                
                anghenghiep.setText(rs.getString("nghenghiep"));
                adiachi.setText(rs.getString("diachi"));
                asdt.setText(rs.getString("sdt"));
                /* Set lựa chọn của buttongroup đối tượng */
                switch(rs.getString("doituong")){
                    case "BHYT":
                        RBbhyt.setSelected(true);
                        break;
                    case "Thu phí":
                        RBthuphi.setSelected(true);
                        break;
                    default:
                        btngroupDoiTuong.clearSelection();
                }
              /* *********************** */
                atennguoithan.setText(rs.getString("tennguoithan"));
                asdtnguoithan.setText(rs.getString("sdtnguoithan"));
                angaynhapvien.setText(rs.getString("vaovien"));
                achuandoan.setText(rs.getString("chuandoan"));
                akhoadieutri.setText(rs.getString("khoadieutri"));
//                akhoadieutri2.setText(rs.getString("khoadieutri"));
                khoa3.setText(rs.getString("khoadieutri"));
                aravien.setText(rs.getString("ravien"));
                alydoravien.setText(rs.getString("lidoravien"));
                /* Set lựa chọn của buttongroup KẾT QUẢ ĐIỀU TRỊ */
                switch(rs.getString("ketquadieutri")){
                    case "Khỏi":
                        RBkhoi.setSelected(true);
                        break;
                    case "Đỡ, giảm":
                        RBdogiam.setSelected(true);
                        break;
                    case "Không thay đổi":
                        RBkhongthaydoi.setSelected(true);
                        break;
                    case "Nặng hơn":
                        RBnanghon.setSelected(true);
                        break;
                    case "Tử vong":
                        RBtuvong.setSelected(true);
                        break;
                    default:
                        btngroupDoiTuong.clearSelection();
                }
              /* *********************** */
                angaytuvong.setText(rs.getString("tuvong"));
                anguyennhantuvong.setText(rs.getString("nguyennhantuvong"));
            }
            }catch(Exception e){
                JOptionPane.showMessageDialog(this,e);
            }
    }
       
 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngroupDoiTuong = new javax.swing.ButtonGroup();
        btngroupGioiTinh = new javax.swing.ButtonGroup();
        btngroupKetQuaDieuTri = new javax.swing.ButtonGroup();
        PanelBIG = new javax.swing.JPanel();
        Pntitletrai = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        khoa3 = new javax.swing.JLabel();
        pntitlephai = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        IDBN = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        pnhanhchinh = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        ahoten = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        angaysinh = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        anghenghiep = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        adiachi = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        atennguoithan = new javax.swing.JTextField();
        asdtnguoithan = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        asdt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        RBbhyt = new javax.swing.JRadioButton();
        RBthuphi = new javax.swing.JRadioButton();
        RBnam = new javax.swing.JRadioButton();
        RBnu = new javax.swing.JRadioButton();
        pnquanlynguoibenh = new javax.swing.JPanel();
        jLabel20 = new javax.swing.JLabel();
        pnvaovien = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        akhoadieutri = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        angaynhapvien = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        achuandoan = new javax.swing.JTextArea();
        jLabel19 = new javax.swing.JLabel();
        pnravien = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        aravien = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        alydoravien = new javax.swing.JTextArea();
        jLabel27 = new javax.swing.JLabel();
        tongngaydieutri = new javax.swing.JTextField();
        pntinhtrang = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        anguyennhantuvong = new javax.swing.JTextArea();
        jLabel26 = new javax.swing.JLabel();
        angaytuvong = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        RBkhoi = new javax.swing.JRadioButton();
        RBdogiam = new javax.swing.JRadioButton();
        RBkhongthaydoi = new javax.swing.JRadioButton();
        RBnanghon = new javax.swing.JRadioButton();
        RBtuvong = new javax.swing.JRadioButton();
        Btnsaveeeeeeee = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(670, 830));

        PanelBIG.setBackground(new java.awt.Color(255, 255, 255));
        PanelBIG.setPreferredSize(new java.awt.Dimension(670, 800));

        Pntitletrai.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("SỞ Y TẾ HÀ NỘI");

        jLabel2.setText("BỆNH VIÊN ĐA KHOA KMA");

        jLabel3.setText("KHOA");

        khoa3.setText("jLabel29");

        javax.swing.GroupLayout PntitletraiLayout = new javax.swing.GroupLayout(Pntitletrai);
        Pntitletrai.setLayout(PntitletraiLayout);
        PntitletraiLayout.setHorizontalGroup(
            PntitletraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PntitletraiLayout.createSequentialGroup()
                .addGroup(PntitletraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PntitletraiLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1))
                    .addGroup(PntitletraiLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PntitletraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(PntitletraiLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(khoa3, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        PntitletraiLayout.setVerticalGroup(
            PntitletraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PntitletraiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PntitletraiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(khoa3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pntitlephai.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("ID BỆNH NHÂN:");

        IDBN.setText("jLabel29");
        IDBN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IDBNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pntitlephaiLayout = new javax.swing.GroupLayout(pntitlephai);
        pntitlephai.setLayout(pntitlephaiLayout);
        pntitlephaiLayout.setHorizontalGroup(
            pntitlephaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntitlephaiLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(IDBN)
                .addContainerGap(59, Short.MAX_VALUE))
        );
        pntitlephaiLayout.setVerticalGroup(
            pntitlephaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntitlephaiLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pntitlephaiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(IDBN))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("BỆNH ÁN BỆNH NHÂN");

        pnhanhchinh.setBackground(new java.awt.Color(255, 255, 255));
        pnhanhchinh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnhanhchinh.setPreferredSize(new java.awt.Dimension(650, 232));

        jLabel6.setText("I. HÀNH CHÍNH");

        jLabel7.setText("1. Họ và tên: ");

        jLabel8.setText("2. Sinh ngày:");

        jLabel9.setText("3. Giới tính:");

        jLabel10.setText("4. Nghề nghiệp:");

        jLabel11.setText("5. Địa chỉ:");

        jLabel12.setText("7. Đối tượng:");

        jLabel13.setText("8. Thông tin người nhà:");

        jLabel14.setText("Họ tên:");

        jLabel15.setText("SĐT");

        jLabel16.setText("6. SĐT");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/png/qrcode.png"))); // NOI18N

        jLabel25.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel25.setText("QR CODE");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel28, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(jLabel25)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel25)
                .addGap(7, 7, 7)
                .addComponent(jLabel28)
                .addContainerGap())
        );

        btngroupDoiTuong.add(RBbhyt);
        RBbhyt.setText("BHYT");
        RBbhyt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBbhytActionPerformed(evt);
            }
        });

        btngroupDoiTuong.add(RBthuphi);
        RBthuphi.setText("Thu phí");
        RBthuphi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBthuphiActionPerformed(evt);
            }
        });

        btngroupGioiTinh.add(RBnam);
        RBnam.setText("Nam");
        RBnam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBnamActionPerformed(evt);
            }
        });

        btngroupGioiTinh.add(RBnu);
        RBnu.setText("Nữ");
        RBnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBnuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnhanhchinhLayout = new javax.swing.GroupLayout(pnhanhchinh);
        pnhanhchinh.setLayout(pnhanhchinhLayout);
        pnhanhchinhLayout.setHorizontalGroup(
            pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnhanhchinhLayout.createSequentialGroup()
                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel12)
                                            .addComponent(jLabel11))
                                        .addGap(18, 18, 18)
                                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                                .addComponent(adiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel16)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(asdt, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                                .addComponent(RBbhyt)
                                                .addGap(18, 18, 18)
                                                .addComponent(RBthuphi))))
                                    .addComponent(jLabel13))
                                .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                    .addComponent(jLabel14)
                                    .addGap(18, 18, 18)
                                    .addComponent(atennguoithan, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel15)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(asdtnguoithan, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(jLabel9)
                                        .addGap(18, 18, 18)
                                        .addComponent(RBnam)
                                        .addGap(10, 10, 10)
                                        .addComponent(RBnu))
                                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(ahoten, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jLabel8))
                                    .addComponent(jLabel10))
                                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(anghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnhanhchinhLayout.createSequentialGroup()
                                        .addGap(11, 11, 11)
                                        .addComponent(angaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        pnhanhchinhLayout.setVerticalGroup(
            pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnhanhchinhLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnhanhchinhLayout.createSequentialGroup()
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(ahoten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(angaysinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(anghenghiep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RBnam)
                            .addComponent(RBnu))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(adiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16)
                            .addComponent(asdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(RBbhyt)
                            .addComponent(RBthuphi))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnhanhchinhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(atennguoithan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15)
                            .addComponent(asdtnguoithan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pnquanlynguoibenh.setBackground(new java.awt.Color(255, 255, 255));
        pnquanlynguoibenh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel20.setText("II. QUẢN LÝ NGƯỜI BỆNH");

        pnvaovien.setBackground(new java.awt.Color(255, 255, 255));
        pnvaovien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("11. Khoa điều trị:");

        jLabel18.setText("9. Ngày vào:");

        achuandoan.setColumns(20);
        achuandoan.setRows(5);
        achuandoan.setAutoscrolls(false);
        achuandoan.setPreferredSize(new java.awt.Dimension(164, 50));
        jScrollPane1.setViewportView(achuandoan);

        jLabel19.setText("10. Chuẩn đoán:");

        javax.swing.GroupLayout pnvaovienLayout = new javax.swing.GroupLayout(pnvaovien);
        pnvaovien.setLayout(pnvaovienLayout);
        pnvaovienLayout.setHorizontalGroup(
            pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnvaovienLayout.createSequentialGroup()
                .addGroup(pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel18)
                    .addComponent(jLabel21))
                .addGap(18, 18, 18)
                .addGroup(pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 198, Short.MAX_VALUE)
                    .addComponent(akhoadieutri)
                    .addComponent(angaynhapvien))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnvaovienLayout.setVerticalGroup(
            pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnvaovienLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(angaynhapvien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnvaovienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(akhoadieutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnravien.setBackground(new java.awt.Color(255, 255, 255));
        pnravien.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel22.setText("12. Ra viện:");

        jLabel24.setText("13. Lý do:");

        aravien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aravienActionPerformed(evt);
            }
        });

        alydoravien.setColumns(20);
        alydoravien.setRows(5);
        alydoravien.setAutoscrolls(false);
        jScrollPane2.setViewportView(alydoravien);

        jLabel27.setText("Tổng số ngày điều trị:");

        javax.swing.GroupLayout pnravienLayout = new javax.swing.GroupLayout(pnravien);
        pnravien.setLayout(pnravienLayout);
        pnravienLayout.setHorizontalGroup(
            pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnravienLayout.createSequentialGroup()
                .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnravienLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel22)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                            .addComponent(aravien)))
                    .addGroup(pnravienLayout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel27)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tongngaydieutri, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnravienLayout.setVerticalGroup(
            pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnravienLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(aravien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(pnravienLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel27)
                    .addComponent(tongngaydieutri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnquanlynguoibenhLayout = new javax.swing.GroupLayout(pnquanlynguoibenh);
        pnquanlynguoibenh.setLayout(pnquanlynguoibenhLayout);
        pnquanlynguoibenhLayout.setHorizontalGroup(
            pnquanlynguoibenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnquanlynguoibenhLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnquanlynguoibenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnquanlynguoibenhLayout.createSequentialGroup()
                        .addComponent(pnvaovien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(pnravien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pnquanlynguoibenhLayout.createSequentialGroup()
                        .addComponent(jLabel20)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        pnquanlynguoibenhLayout.setVerticalGroup(
            pnquanlynguoibenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnquanlynguoibenhLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel20)
                .addGap(11, 11, 11)
                .addGroup(pnquanlynguoibenhLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnravien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnvaovien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pntinhtrang.setBackground(new java.awt.Color(255, 255, 255));
        pntinhtrang.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pntinhtrang.setPreferredSize(new java.awt.Dimension(650, 130));

        jLabel23.setText("14. Kết quả điều trị:");

        anguyennhantuvong.setColumns(20);
        anguyennhantuvong.setRows(5);
        jScrollPane5.setViewportView(anguyennhantuvong);

        jLabel26.setText("15. Tử vong");

        angaytuvong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                angaytuvongActionPerformed(evt);
            }
        });

        jLabel30.setText("Nguyên nhân:");

        jLabel17.setText("III. TÌNH TRẠNG RA VIỆN");

        btngroupKetQuaDieuTri.add(RBkhoi);
        RBkhoi.setText("Khỏi");
        RBkhoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBkhoiActionPerformed(evt);
            }
        });

        btngroupKetQuaDieuTri.add(RBdogiam);
        RBdogiam.setText("Đỡ, giảm");
        RBdogiam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBdogiamActionPerformed(evt);
            }
        });

        btngroupKetQuaDieuTri.add(RBkhongthaydoi);
        RBkhongthaydoi.setText("Không thay đổi");
        RBkhongthaydoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBkhongthaydoiActionPerformed(evt);
            }
        });

        btngroupKetQuaDieuTri.add(RBnanghon);
        RBnanghon.setText("Nặng hơn");
        RBnanghon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBnanghonActionPerformed(evt);
            }
        });

        btngroupKetQuaDieuTri.add(RBtuvong);
        RBtuvong.setText("Tử vong");
        RBtuvong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RBtuvongActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pntinhtrangLayout = new javax.swing.GroupLayout(pntinhtrang);
        pntinhtrang.setLayout(pntinhtrangLayout);
        pntinhtrangLayout.setHorizontalGroup(
            pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntinhtrangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pntinhtrangLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(pntinhtrangLayout.createSequentialGroup()
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel23)
                            .addGroup(pntinhtrangLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(RBkhongthaydoi)
                                    .addGroup(pntinhtrangLayout.createSequentialGroup()
                                        .addComponent(RBkhoi)
                                        .addGap(18, 18, 18)
                                        .addComponent(RBdogiam))))
                            .addGroup(pntinhtrangLayout.createSequentialGroup()
                                .addGap(115, 115, 115)
                                .addComponent(RBnanghon)
                                .addGap(7, 7, 7)
                                .addComponent(RBtuvong)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 96, Short.MAX_VALUE)
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jLabel26, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane5)
                            .addComponent(angaytuvong, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))))
        );
        pntinhtrangLayout.setVerticalGroup(
            pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pntinhtrangLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(pntinhtrangLayout.createSequentialGroup()
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(angaytuvong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(6, 6, 6)
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pntinhtrangLayout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBkhoi)
                            .addComponent(RBdogiam))
                        .addGap(5, 5, 5)
                        .addGroup(pntinhtrangLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RBkhongthaydoi)
                            .addComponent(RBnanghon)
                            .addComponent(RBtuvong))))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        Btnsaveeeeeeee.setText("Lưu thay đổi");
        Btnsaveeeeeeee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnsaveeeeeeeeActionPerformed(evt);
            }
        });

        jButton2.setText("Đóng");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBIGLayout = new javax.swing.GroupLayout(PanelBIG);
        PanelBIG.setLayout(PanelBIGLayout);
        PanelBIGLayout.setHorizontalGroup(
            PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBIGLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelBIGLayout.createSequentialGroup()
                        .addComponent(Pntitletrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel5)
                        .addGap(76, 76, 76)
                        .addComponent(pntitlephai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelBIGLayout.createSequentialGroup()
                        .addGroup(PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pntinhtrang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(pnquanlynguoibenh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(pnhanhchinh, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
            .addGroup(PanelBIGLayout.createSequentialGroup()
                .addGap(236, 236, 236)
                .addComponent(Btnsaveeeeeeee)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        PanelBIGLayout.setVerticalGroup(
            PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBIGLayout.createSequentialGroup()
                .addGroup(PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelBIGLayout.createSequentialGroup()
                        .addGap(84, 92, Short.MAX_VALUE)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18))
                    .addGroup(PanelBIGLayout.createSequentialGroup()
                        .addGroup(PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pntitlephai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, PanelBIGLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Pntitletrai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(pnhanhchinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnquanlynguoibenh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pntinhtrang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(PanelBIGLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Btnsaveeeeeeee)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBIG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelBIG, javax.swing.GroupLayout.DEFAULT_SIZE, 833, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void aravienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aravienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_aravienActionPerformed

    private void angaytuvongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_angaytuvongActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_angaytuvongActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
         //nút đóng Jframe 
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void BtnsaveeeeeeeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnsaveeeeeeeeActionPerformed
        try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost/qlbv","root","");
            String sql = "UPDATE benhnhan SET hoten=? ,ngaysinh=? ,gioitinh=? ,nghenghiep=? ,diachi=? ,"
                    + "sdt=? ,doituong=? ,tennguoithan=? ,sdtnguoithan=? ,vaovien=? ,chuandoan=? ,"
                    + "khoadieutri=? ,ravien=? ,lidoravien=? ,ketquadieutri=? ,tuvong=? ,nguyennhantuvong=?  WHERE id=?";
            PreparedStatement ptst = conn.prepareStatement(sql);
            ptst.setString(18, IDBN.getText());
            ptst.setString(1, ahoten.getText());
            ptst.setString(2, angaysinh.getText());
            ptst.setString(3, xgioitinh);
            ptst.setString(4, anghenghiep.getText());
            ptst.setString(5, adiachi.getText());
            ptst.setString(6, asdt.getText());
            ptst.setString(7, xdoituong);
            ptst.setString(8, atennguoithan.getText());
            ptst.setString(9, asdtnguoithan.getText());
            ptst.setString(10, angaynhapvien.getText());
            ptst.setString(11, achuandoan.getText());
            ptst.setString(12, akhoadieutri.getText());
            ptst.setString(13, aravien.getText());
            ptst.setString(14, alydoravien.getText());
            ptst.setString(15, xketquadieutri);
            ptst.setString(16, angaytuvong.getText());
            ptst.setString(17, anguyennhantuvong.getText());
            ptst.executeUpdate();
            JOptionPane.showMessageDialog(this,"Cập nhật dữ liệu thành công!");
            LoadData();
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        }   
    }//GEN-LAST:event_BtnsaveeeeeeeeActionPerformed

    private void RBkhoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBkhoiActionPerformed
        xketquadieutri = "Khỏi";
    }//GEN-LAST:event_RBkhoiActionPerformed

    private void RBdogiamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBdogiamActionPerformed
        xketquadieutri = "Đỡ, giảm";
    }//GEN-LAST:event_RBdogiamActionPerformed

    private void RBkhongthaydoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBkhongthaydoiActionPerformed
        xketquadieutri = "Không thay đổi";
    }//GEN-LAST:event_RBkhongthaydoiActionPerformed

    private void RBnanghonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnanghonActionPerformed
        xketquadieutri = "Nặng hơn";
    }//GEN-LAST:event_RBnanghonActionPerformed

    private void RBtuvongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBtuvongActionPerformed
        xketquadieutri = "Tử vong";
    }//GEN-LAST:event_RBtuvongActionPerformed

    private void RBbhytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBbhytActionPerformed
        xdoituong = "BHYT";
    }//GEN-LAST:event_RBbhytActionPerformed

    private void RBthuphiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBthuphiActionPerformed
        xdoituong = "Thu phí";
    }//GEN-LAST:event_RBthuphiActionPerformed

    private void RBnamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnamActionPerformed
        xgioitinh = "Nam";
    }//GEN-LAST:event_RBnamActionPerformed

    private void RBnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RBnuActionPerformed
        xgioitinh = "Nữ";
    }//GEN-LAST:event_RBnuActionPerformed

    private void IDBNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IDBNMouseClicked
        LoadData();
    }//GEN-LAST:event_IDBNMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(benhanbenhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(benhanbenhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(benhanbenhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(benhanbenhnhan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new benhanbenhnhan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btnsaveeeeeeee;
    private javax.swing.JLabel IDBN;
    private javax.swing.JPanel PanelBIG;
    private javax.swing.JPanel Pntitletrai;
    private javax.swing.JRadioButton RBbhyt;
    private javax.swing.JRadioButton RBdogiam;
    private javax.swing.JRadioButton RBkhoi;
    private javax.swing.JRadioButton RBkhongthaydoi;
    private javax.swing.JRadioButton RBnam;
    private javax.swing.JRadioButton RBnanghon;
    private javax.swing.JRadioButton RBnu;
    private javax.swing.JRadioButton RBthuphi;
    private javax.swing.JRadioButton RBtuvong;
    private javax.swing.JTextArea achuandoan;
    private javax.swing.JTextField adiachi;
    private javax.swing.JTextField ahoten;
    private javax.swing.JTextField akhoadieutri;
    private javax.swing.JTextArea alydoravien;
    private javax.swing.JTextField angaynhapvien;
    private javax.swing.JTextField angaysinh;
    private javax.swing.JTextField angaytuvong;
    private javax.swing.JTextField anghenghiep;
    private javax.swing.JTextArea anguyennhantuvong;
    private javax.swing.JTextField aravien;
    private javax.swing.JTextField asdt;
    private javax.swing.JTextField asdtnguoithan;
    private javax.swing.JTextField atennguoithan;
    private javax.swing.ButtonGroup btngroupDoiTuong;
    private javax.swing.ButtonGroup btngroupGioiTinh;
    private javax.swing.ButtonGroup btngroupKetQuaDieuTri;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel khoa3;
    private javax.swing.JPanel pnhanhchinh;
    private javax.swing.JPanel pnquanlynguoibenh;
    private javax.swing.JPanel pnravien;
    private javax.swing.JPanel pntinhtrang;
    private javax.swing.JPanel pntitlephai;
    private javax.swing.JPanel pnvaovien;
    private javax.swing.JTextField tongngaydieutri;
    // End of variables declaration//GEN-END:variables
}
